"""ask-chatgpt v2 rewrite scaffold."""

from ask_chatgpt.allowlist import DEFAULT_ALLOWED_HOST_SUFFIXES, Allowlist
from ask_chatgpt.errors import (
    AskChatGPTError,
    AttachmentFetchError,
    AttachmentNotFoundError,
    AttachmentUploadError,
    BackendAuthUnavailableError,
    BackendCaptureShapeError,
    CDPUnreachableError,
    CaptureFailedClosedError,
    CompletionTimeoutError,
    ConversationNotFoundError,
    DomainNotAllowedError,
    HumanActionNeededError,
    InternalError,
    MaxTotalWaitExceededError,
    ModelSelectionNotReflectedError,
    PromptNotSubmittedError,
    SelectorNotFoundError,
    StoreError,
    StoreWarning,
    TabPoolExhaustedError,
    ToolSelectionNotReflectedError,
)
from ask_chatgpt.identity import (
    ConversationRef,
    backend_conversation_url,
    conversation_url,
    normalize_conversation_id,
    parse_conversation_address,
    parse_project_address,
)
from ask_chatgpt.models import (
    AttachmentRef,
    AttachmentSpec,
    CaptureFidelity,
    CaptureSource,
    CitationRef,
    JsonValue,
    ModelRef,
    PreflightResult,
    SelectorMap,
    SendTimeouts,
    StatusReport,
    Transcript,
    TurnRecord,
    TurnRole,
    TurnStatus,
)
from ask_chatgpt.selectors import load_selector_map
from ask_chatgpt.session import Session
from ask_chatgpt.store import ConversationPaths, Store, emit_payload

__version__ = "0.3.0"

__all__ = [
    "__version__",
    "Allowlist",
    "AskChatGPTError",
    "AttachmentFetchError",
    "AttachmentNotFoundError",
    "AttachmentUploadError",
    "AttachmentRef",
    "AttachmentSpec",
    "BackendAuthUnavailableError",
    "BackendCaptureShapeError",
    "CDPUnreachableError",
    "CaptureFailedClosedError",
    "CaptureFidelity",
    "CaptureSource",
    "CitationRef",
    "CompletionTimeoutError",
    "ConversationNotFoundError",
    "ConversationPaths",
    "ConversationRef",
    "DEFAULT_ALLOWED_HOST_SUFFIXES",
    "DomainNotAllowedError",
    "HumanActionNeededError",
    "InternalError",
    "JsonValue",
    "MaxTotalWaitExceededError",
    "ModelRef",
    "ModelSelectionNotReflectedError",
    "PreflightResult",
    "PromptNotSubmittedError",
    "SelectorMap",
    "SelectorNotFoundError",
    "SendTimeouts",
    "Session",
    "StatusReport",
    "Store",
    "StoreError",
    "StoreWarning",
    "TabPoolExhaustedError",
    "ToolSelectionNotReflectedError",
    "Transcript",
    "TurnRecord",
    "TurnRole",
    "TurnStatus",
    "backend_conversation_url",
    "conversation_url",
    "emit_payload",
    "load_selector_map",
    "normalize_conversation_id",
    "parse_conversation_address",
    "parse_project_address",
]
